name: Build and Release
 
on:
  push:
    tags:
      - 'v*' # 当推送 v 开头的标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    container:
      image: debian:10
    timeout-minutes: 300
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.8'
            arch: x64
          # - os: ubuntu-24.04-arm #ubuntu-latest-arm
          #   python-version: '3.8'
          #   arch: arm64

    steps:
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: ${{ matrix.python-version }}
    #     architecture: ${{ matrix.arch }}

    - name: Set up
      run: |
        apt update
        apt install wget tar xz-utils git python3 python3-pip gawk autoconf automake python3-cmarkgfm -y
        wget --version
        git config --global --add safe.directory ${{ github.workspace }}
        # pip3 install cmarkgfm

    - name: Check Environment
      run: |
        uname -a
        ldd --version

    - uses: actions/checkout@v3

    - name: Build
      run: bash build_static.sh

    - name: Checksum
      run: |
        sha256sum rsync-aarch64
        sha256sum rsync-x86_64

    - name: Create Github Release
      id: create_release
      uses: softprops/action-gh-release@v2.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          rsync-aarch64
          rsync-x86_64